services:
  nekkochat.server:
    build:
      context: .
      dockerfile: NekkoChat.Server/Dockerfile
    container_name: "nekkochat.server"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:7198
        - REDIS_HOST=cache
        - REDIS_PORT=6379
    ports:
        - '7198:7198'    

  nekkochat.client:
    build:
      context: ./nekkochat.client
      dockerfile: Dockerfile
    container_name: "nekkochat.client"
    environment:
        NODE_ENV: "development"
        HTTPS_PROXY: "https://+:7198"
    ports:
        - '5173:5173'
    volumes:
        - ./nekkochat.client/certificates:/usr/src/app/certificates
    command: npm run dev
    
  nekkochat.redis:
    image: "redis/redis-stack"
    container_name: "nekkochat.redis"
    ports:
        - '6379:6379'
    volumes:
        - cache:/data
  
    
  nekkochat.database:
    image: "postgres:latest"
    container_name: "nekkochat.database"
    environment:
        - POSTGRES_DB=nekkoDB
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports: 
        - "5432:5432"
    volumes:
        - ./.containers/nekkoDB:/var/lib/postgresql/data
        - ./NekkoChat.Server/Constants/init.sql:/docker-entrypoint-initdb.d/init.sql
   
  
volumes:   
    cache:
        driver: local
    